config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => 'home#about', as: 'about'
  root "home#top"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :books, only: [:new, :create, :index, :show, :edit, :update]
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :users, only: [:show, :index, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, length: {minimum: 2,maximum: 20}
  validates :introduction, length: {maximum: 50}
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  before_validation :set_address
  include JpPrefecture
  jp_prefecture :prefecture_code
  def set_address
    self.address=prefecture_name+address_city+address_street
  end
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
  #登録時にメールアドレスを不要とする
  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  #def create
      #build_resource(sign_up_params)
      #resource.address = "#{resource.address_city}#{resource.address_street}"
      #resource.save
       #yield resource if block_given?
      #if resource.persisted?
      #if resource.active_for_authentication?
        #set_flash_message! :notice, :signed_up
        #sign_up(resource_name, resource)
        #respond_with resource, location: after_sign_up_path_for(resource)
      #else
        #set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        #expire_data_after_sign_in!
        #respond_with resource, location: after_inactive_sign_up_path_for(resource)
      #end
    #else
      #clean_up_passwords resource
      #set_minimum_password_length
      #respond_with resource
    #end
  #end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
  	  @user = User.find(params[:id])
  	  @book = Book.new
  	  @books = Book.all
  end

  def index
  	  @users = User.all
  	  @book = Book.new
  	  @books = Book.all
  end
  def edit
  	  @user = User.find(params[:id])
      unless @user.id == current_user.id
        redirect_to user_path(current_user)
      end
  end
  def update
  	  @user = User.find(params[:id])
      
      if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
      else
        render 'edit'

      end
      
  end

  private 
  def user_params
      params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-xs-3">
    	<h2>User info</h2>
    		<%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: " ", fallback: "no_image.jpg" %> 
    		<table class="table">
      			<tbody>
      				<tr></tr> 
      				<tr>
    	  				<th>name</th>
    	  				<th><%= user.name %></th>
      				</tr>
      				<tr>
    	  				<th>introduction</th>
    	  				<th><%= user.introduction %></th>
      				</tr>
	  			</tbody>
	  		</table>
		<div class="row">
	     	<p><%= link_to "", edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%></p>
        </div>
        <h2>New book</h2>

 <% if book.errors.any? %>
    <ul>
      <%= book.errors.count %><span>error</span>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>

<% end %>
<!-- form_for部分 -->
<%= form_for(book) do |f| %>
	<div class="field row"
    <label>Title</label>
    <%= f.text_field :title, class:"col-xs-12"%>
 	</div>
 	<div class="field row"
    <label>Opinion</label>
    <%= f.text_area :opinion, class:"col-xs-12" %>
	</div><br>
 	<div class="actions row">
    <%= f.submit 'Create Book',class:"btn btn-primary col-xs-12" %>
  </div>


<% end %>

    <p id="notice"></p>
</div>

app/views/users/edit.html.erb
<div class="body">
   <div class="container"> <!-- ここを追加 -->
      <div class="row">
        <div class="col-xs-3">
<% if @user.errors.any? %>
              <ul>
                  <%= @user.errors.count %><span>error</span>
                  <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
              </ul>
          <% end %>
        <h2>User info</h2>


         <%= form_for(@user) do |f| %>

            <label for="user_name">Name</label>
            <%= f.text_field :name, autofocus: true, class:"form-control", placeholder:"名前"%>

            <label for="user_image">Image</label>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
            <label for="user_introduction">Introduction</label>
            <%= f.text_field :introduction, autofocus: true, class:"form-control", id:"inputEmail", placeholder:""%>
            <%= f.submit "Update User" %>
          <% end %>
        </div>
      </div>
   </div>
</div>

app/views/users/index.html.erb
<div class="body">
    <div class="container">
      <div class="row">
          <div class="col-xs-3">
          <h2>User info</h2>
          <%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, format: 'jpeg', class: " ", fallback: "no_image.jpg" %> 
          <table class="table">
              <tbody>
                <tr></tr> 
                <tr>
                  <th>name</th>
                  <th><%= current_user.name %></th>
                </tr>
                <tr>
                  <th>introduction</th>
                  <th><%= current_user.introduction %></th>
                </tr>
            </tbody>
          </table>
        <div class="row">
            <%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>
        </div>
            <h2>New book</h2>
          <% if @book.errors.any? %>
              <ul>
                  <%= @book.errors.count %><span>error</span>
                  <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
              </ul>
          <% end %>

        <%= form_for(@book) do |f| %>
          <div class="field row">
              <label>Title</label>
              <%= f.text_field :title, class:"col-xs-12"%>
          </div>
          <div class="field row">
              <label>Opinion</label>
              <%= f.text_area :body, class:"col-xs-12" %>
          </div><br>
          <div class="actions row">
              <%= f.submit 'Create Book',class:"btn btn-primary col-xs-12" %>
            </div>
        <% end %>
      </div>
      <div class="col-xs-9">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, :fill, 20, 20, format: 'jpeg', class: " ", fallback: "no_image.jpg" ,size:'20x20' %></td> 
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user) %><td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      
  </div>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="body">
    <div class="container">
    	<div class="row">
    		<% if flash[:notice] %>
			      <div class="flash">
			        <p><%= flash[:notice] %></p>
			      </div>
			    <% end %>
      		<div class="col-xs-3">
      			
    			<h2>User info</h2>
    			<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: " ", fallback: "no_image.jpg" %> 
    			<table class="table">
	      			<tbody>
	      				<tr></tr> 
	      				<tr>
	    	  				<th>name</th>
	    	  				<th><%= @user.name %></th>
	      				</tr>
	      				<tr>
	    	  				<th>introduction</th>
	    	  				<th><%= @user.introduction %></th>
	      				</tr>
		  			</tbody>
	  			</table>
				<div class="row">
					          <% if @user == current_user %>
<%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>
<% else %>
<%= link_to "", user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>
<% end %>
		     		
	        	</div>
	        	<h2>New book</h2>
		 			<% if @book.errors.any? %>
		    			<ul>
		      				<%= @book.errors.count %><span>error</span>
		      				<% @book.errors.full_messages.each do |message| %>
		        			<li><%= message %></li>
		      				<% end %>
		    			</ul>
					<% end %>

				<%= form_for(@book) do |f| %>
					<div class="field row">
				    	<label>Title</label>
				    	<%= f.text_field :title, class:"col-xs-12"%>
				 	</div>
				 	<div class="field row">
					    <label>Opinion</label>
					    <%= f.text_area :body, class:"col-xs-12" %>
					</div><br>
				 	<div class="actions row">
				    	<%= f.submit 'Create Book',class:"btn btn-primary col-xs-12" %>
				  	</div>
				<% end %>
			</div>
			<div class="col-xs-9">
				<h2>Books</h2>
					<table class="table table-hover table-inverse">
					  <thead>
					    <tr>
					      <th></th>
					      <th>Title</th>
					      <th>Opinion</th>
					      <th colspan="3"></th>
					    </tr>
					  </thead>

					  <tbody>
					      <% @books.each do |book| %><% if book.user == @user %>
					      <tr>
					      	<td><%= attachment_image_tag @user, :profile_image, :fill, 20, 20, format: 'jpeg', class: " pull-left ", fallback: "no_image.jpg" %> </td>
					        <td class="book-title1"><%= link_to book.title, book_path(book) %></td>
					        <td ><%= book.body %></td>
					      </tr>

					     <% end %>
					     <% end %>
					  </tbody>
					</table>
  			</div>
  		</div>
  		<div><br>
  			<% if @user.id == current_user.id %>
  		<div class="container">
  				<script type="text/javascript">
					  function initMap() {
					    var test ={lat: <%= @user.latitude %>, lng: <%= @user.longitude %>};
					    var map = new google.maps.Map(document.getElementById('map'), {
					              zoom: 15, 
					              center: test
					              });
					    var transitLayer = new google.maps.TransitLayer();
					    transitLayer.setMap(map);

					    var contentString = '住所：<%= @user.address %>';
					    var infowindow = new google.maps.InfoWindow({
					      content: contentString
					    });


					    var marker = new google.maps.Marker({
					                  position:test,
					                  map: map,
					                  title: contentString
					                 });

					     marker.addListener('click', function() {
					       infowindow.open(map, marker);
					     });
					  }
					</script>

					<script async defer
              				src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['API_KEY'] %>&callback=initMap">
					</script>
					<style type="text/css">
					  #map { height: 300px;
					         width: 90%;}
					</style>

					<div id="map"></div>
 	</div><% end %>
</div>