config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => 'home#about', as: 'about'
  root "home#top"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :books, only: [:new, :create, :index, :show, :edit, :update]
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :users, only: [:show, :index, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
  	validates :title, presence:true
	validates :body, presence:true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
    def top
    end
    def create
  	  @book = Book.new(book_params)
  	  @book.user_id = current_user.id
  	  if @book.save
      flash[:notice] = "You have creatad book successfully."
  	  redirect_to book_path(@book.id)
      else

        @books = Book.all
        render 'index'

      end
    end
    def index
  	  @book = Book.new
  	  @books = Book.all
    end
    def show
    	@book = Book.new
  	  @book1 = Book.find(params[:id])
      @user = @book1.user
    end
    def destroy
    @book1 = Book.find(params[:id])
    @book1.destroy
    redirect_to books_path
end
 def edit
      @book = Book.find(params[:id])
      unless @book.user_id == current_user.id
        redirect_to books_path
      end

  end

  def update
      @book = Book.find(params[:id])

      if @book.update(book_params)
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
      else
        render 'edit'

      end
  end
		def book_params
  	  	params.require(:book).permit(:title, :body)
		end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="body">
      <div class="container">

        <p id="notice"></p>


      	<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>Editing Book</h1>
  <!-- <div class='col-md-3 col-md-offset-3'>
  </div> --><% if @book.errors.any? %>
		    			<ul>
		      				<%= @book.errors.count %><span>error</span>
		      				<% @book.errors.full_messages.each do |message| %>
		        			<li><%= message %></li>
		      				<% end %>
		    			</ul>
					<% end %>
				<%= form_for(@book) do |f| %>
					<div class="field row">
				    	<label>Title</label>
				    	<%= f.text_field :title, class:"col-xs-12"%>
				 	</div>
				 	<div class="field row">
					    <label>Opinion</label>
					    <%= f.text_area :body, class:"col-xs-12" %>
					</div><br>
				 	<div class="actions row">
				    	<%= f.submit 'Update Book',class:"btn btn-primary col-xs-12" %>
				  	</div>
				<% end %>
		<%= link_to "Show", book_path(@book) %> |
		<%= link_to "Back", books_path %>
    </div>
    <div class="col-md-3"></div>
</div>
      </div>
    </div>

app/views/books/index.html.erb
<div class="body">
    <div class="container">
      <div class="row">
          <div class="col-xs-3">
          <h2>User info</h2>
          <%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, format: 'jpeg', class: " ", fallback: "no_image.jpg" %> 
          <table class="table">
              <tbody>
                <tr></tr> 
                <tr>
                  <th>name</th>
                  <th><%= current_user.name %></th>
                </tr>
                <tr>
                  <th>introduction</th>
                  <th><%= current_user.introduction %></th>
                </tr>
            </tbody>
          </table>
        <div class="row">

            <%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>
        </div>
            <h2>New book</h2>
          <% if @book.errors.any? %>
              <ul>
                  <%= @book.errors.count %><span>error</span>
                  <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
              </ul>
          <% end %>

        <%= form_for(@book) do |f| %>
          <div class="field row">
              <label>Title</label>
              <%= f.text_field :title, class:"col-xs-12"%>
          </div>
          <div class="field row">
              <label>Opinion</label>
              <%= f.text_area :body, class:"col-xs-12" %>
          </div><br>
          <div class="actions row">
              <%= f.submit 'Create Book',class:"btn btn-primary col-xs-12" %>
            </div>
        <% end %>
      </div>
<div class="col-xs-9">
<h1>Books</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user_id) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 20, 20, format: 'jpeg', class: " pull-left ", fallback: "no_image.jpg",size:'20x20' %> <% end %></td>
        <td><%= link_to book.title,book_path(book) %></td>
        <td><%= book.body %></td>
      </tr>
     <% end %>
  </tbody>
</table>
</div>
  </div>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="body">
    <div class="container">
      <div class="row">
          <div class="col-xs-3">
            <% if flash[:notice] %>
              <div class="flash">
                <%= flash[:notice] %>
              </div>
            <% end %>
          <h2>User info</h2>
          <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: " ", fallback: "no_image.jpg" %> 
          <table class="table">
              <tbody>
                <tr></tr> 
                <tr>
                  <th>name</th>
                  <th><%= @user.name %></th>
                </tr>
                <tr>
                  <th>introduction</th>
                  <th><%= @user.introduction %></th>
                </tr>
            </tbody>
          </table>
        <div class="row">
            
                            <% if @user == current_user %>
<%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>
<% else %>
<%= link_to "", user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>
<% end %>
</div>
            <h2>New book</h2>
          <% if @book.errors.any? %>
              <ul>
                  <%= @book.errors.count %><span>error</span>
                  <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
              </ul>
          <% end %>

        <%= form_for(@book) do |f| %>
          <div class="field row">
              <label>Title</label>
              <%= f.text_field :title, class:"col-xs-12"%>
          </div>
          <div class="field row">
              <label>Opinion</label>
              <%= f.text_area :body, class:"col-xs-12" %>
          </div><br>
          <div class="actions row">
              <%= f.submit 'Create Book',class:"btn btn-primary col-xs-12" %>
            </div>
        <% end %>
      </div>
      <div class="col-xs-9">
        <h2>Book detail</h2>
          <table class="table">
            <tbody>
                <tr>
                  <td><%= link_to user_path(@user) do %>
                    <%= attachment_image_tag @user, :profile_image, :fill, 20, 20, format: 'jpeg', class: " pull-left ", fallback: "no_image.jpg",size:'20x20' %>
                    <br><%= @user.name %><% end %>

                     </td>

                  <td><%= link_to @book1.title,book_path(@book1) %></td>
                  <td><%= @book1.body %></td>
                  <% if @user == current_user %>
                  <td><%= link_to "Edit", edit_book_path(@book1),class:"btn-sm btn-success" %><td>
                  <td><%= link_to "Destroy", destroy_book_path(@book1), class:"btn-sm btn-danger",method: :delete, "data-confirm" => "本当に消しますか？" %>
                    <% end %>
                  </td>
                </tr>

            </tbody>
          </table>
      

  </div>
      </div>
    </div>
</div>
</div>